# Generated by Django 5.2.17 on 2026-09-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cache_threshold',
            field=models.FloatField(default=0.95),
        ),
    ]
