# Generated by Django 5.2.17 on 2026-09-15 06:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('provider', models.CharField(max_length=50)),
                ('input_cost_per_1k', models.DecimalField(decimal_places=6, max_digits=10)),
                ('output_cost_per_1k', models.DecimalField(decimal_places=6, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=50, unique=True)),
                ('monthly_request_limit', models.IntegerField(default=100)),
                ('requests_per_minute', models.IntegerField(default=10)),
                ('cache_ttl_seconds', models.IntegerField(default=3600)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('key_prefix', models.CharField(editable=False, max_length=16)),
                ('key_hash', models.CharField(editable=False, max_length=255)),
                ('permissions', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('admin', 'Admin')], default='write', max_length=20)),
                ('rate_limit_override', models.IntegerField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('void', 'Void')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.organization')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timeout_seconds', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('fallback_models', models.ManyToManyField(blank=True, related_name='fallback_rules', to='billing.modelconfig')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='billing.plan')),
                ('primary_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_rules', to='billing.modelconfig')),
            ],
            options={
                'ordering': ['plan__name'],
                'unique_together': {('plan', 'primary_model')},
            },
        ),
        migrations.CreateModel(
            name='UsageAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('month', models.CharField(max_length=7)),
                ('total_requests', models.IntegerField(default=0)),
                ('input_tokens', models.BigIntegerField(default=0)),
                ('output_tokens', models.BigIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('cache_hits', models.IntegerField(default=0)),
                ('cache_savings', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_aggregates', to='accounts.organization')),
            ],
            options={
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['organization', 'month'], name='billing_usa_organiz_2a5bea_idx')],
                'unique_together': {('organization', 'month')},
            },
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(max_length=255)),
                ('model_used', models.CharField(max_length=255)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('cache_hit', models.BooleanField(default=False)),
                ('request_id', models.CharField(blank=True, max_length=36, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('month', models.CharField(default='', editable=False, max_length=7)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='billing.apikey')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='accounts.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['organization', 'timestamp'], name='billing_usa_organiz_b96d14_idx'), models.Index(fields=['organization', 'month'], name='billing_usa_organiz_fe093e_idx'), models.Index(fields=['api_key_id'], name='billing_usa_api_key_36795b_idx')],
            },
        ),
    ]
