# Generated by Django 5.2.17 on 2026-09-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='permissions',
            field=models.CharField(choices=[('write', 'Full Access (Read/Write/Query)'), ('rag:query', 'RAG Query Only (rag:query)'), ('documents:write', 'Documents Write Only (documents:write)'), ('documents:read', 'Documents Read Only (documents:read)'), ('read', 'Read Only (Legacy)'), ('admin', 'Admin (Legacy)'), ('admin:*', 'Admin Full Control (admin:*)')], default='write', max_length=50),
        ),
        migrations.AlterField(
            model_name='routingrule',
            name='timeout_seconds',
            field=models.IntegerField(default=60),
        ),
    ]
