[pytest]
DJANGO_SETTINGS_MODULE = config.test_settings
testpaths = tests
norecursedirs = .venv venv node_modules .git
python_files = tests.py test_*.py *_tests.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --reuse-db
