# Generated by Django 5.2.17 on 2026-09-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cacheentry',
            name='embedding_vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
