# Generated by Django 5.2.17 on 2026-09-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0002_cacheentry_embedding_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
