# Generated by Django 5.2.17 on 2026-09-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0003_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquery',
            name='source_doc_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
